project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "assignment_gretl.qmd"
    - "assignment_r.qmd"
    - "assignments_formats.qmd"
#    - "AIrep/qmdrds/conv.qmd"

website:
  title: "OEKA201AssignmentOPAMPJ"
  navbar:
    left:
      -  text: Home
         href: index.qmd
      -  text: Bjørnar's assignment using Gretl
         href: assignment_gretl.qmd
      -  text: Bjørnar's assignment using R
         href: assignment_r.qmd
      -  text: Assignments
         href: assignsments_formats.qmd
    right:
      - text: AI-conversation
#        href: AIrep/qmdrds/conv.qmd

format:
  html:
    toc: true
# Test
  docx:
    toc: true
  pdf:
    toc: true
# Add more stuff here
  epub:
    toc: true
# Add more stuff here
# bibliography: ref.bib





